"""Bilingual Keep-a-Changelog rendering.

Both languages share one neutral model (a list of
:class:`~tools.changelog.model.ReleaseSegment`); only the label table
differs.  Output is deterministic — same input, same bytes — so ``generate
--check`` can diff against the files on disk.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping

from . import gitee
from .model import Category, Commit, ReleaseSegment
from .translations import OverrideEntry

#: Rendering order after the breaking-changes group.
_CATEGORY_ORDER: tuple[Category, ...] = (
    Category.FEATURE,
    Category.FIX,
    Category.PERFORMANCE,
    Category.REFACTOR,
    Category.DOCS,
    Category.TEST,
    Category.TOOLING,
    Category.OTHER,
)

_LABELS: dict[str, dict[Category, str]] = {
    "en": {
        Category.FEATURE: "Features",
        Category.FIX: "Bug Fixes",
        Category.PERFORMANCE: "Performance",
        Category.REFACTOR: "Refactors",
        Category.DOCS: "Documentation",
        Category.TEST: "Tests",
        Category.TOOLING: "Tooling",
        Category.OTHER: "Other Changes",
    },
    "zh": {
        Category.FEATURE: "新功能",
        Category.FIX: "问题修复",
        Category.PERFORMANCE: "性能优化",
        Category.REFACTOR: "重构",
        Category.DOCS: "文档",
        Category.TEST: "测试",
        Category.TOOLING: "构建与工程",
        Category.OTHER: "其他变更",
    },
}

_BREAKING_LABELS: dict[str, str] = {
    "en": "⚠ BREAKING CHANGES",
    "zh": "⚠ 破坏性变更",
}

_UNRELEASED_LABELS: dict[str, str] = {"en": "Unreleased", "zh": "未发布"}

_INITIAL_NOTES: dict[str, str] = {
    "en": "_Initial release._",
    "zh": "_首个版本。_",
}

_HEADERS: dict[str, str] = {
    "en": (
        "# Changelog\n"
        "\n"
        "> Generated by `python -m tools.changelog` — do not edit by hand.\n"
        "> Chinese edition: [CHANGELOG.zh.md](CHANGELOG.zh.md)"
    ),
    "zh": (
        "# 变更日志\n"
        "\n"
        "> 本文件由 `python -m tools.changelog` 自动生成 —— 请勿手工编辑。\n"
        "> 英文版：[CHANGELOG.md](CHANGELOG.md)"
    ),
}

# The bundled copies (yate/resources/changelog.*.md) address end users, so
# the header carries neither the "do not edit" wording nor a sibling link.
_BUNDLE_HEADERS: dict[str, str] = {"en": "# Changelog", "zh": "# 变更日志"}

_MISSING_ZH_MARK = "[缺中文]"
_UNPUSHED_MARKS: dict[str, str] = {"en": "(unpushed)", "zh": "(本地未推送)"}

_UNRELEASED_HEADINGS: tuple[str, ...] = ("## [Unreleased]", "## [未发布]")


def strip_unreleased(doc: str) -> str:
    """Drop the Unreleased section from a rendered document.

    Freshness gating (``generate --check`` / ``check``) ignores Unreleased:
    commits that merely maintain the changelog itself always lag one commit
    behind the files on disk, and the section is refreshed wholesale at each
    release by ``generate``.
    """
    kept: list[str] = []
    skipping = False
    for line in doc.split("\n"):
        # the heading may carry a " · [compare](...)" suffix
        if line.startswith(_UNRELEASED_HEADINGS):
            skipping = True
            continue
        if skipping and line.startswith("## "):
            skipping = False
        if not skipping:
            kept.append(line)
    return "\n".join(kept)


def split_sections(doc: str) -> dict[str, str]:
    """Slice a rendered document at ``^## `` headings into version sections.

    Returns ``{heading line: section text}`` where each section spans from
    its heading to just before the next heading.  The file header (before
    the first ``## ``) is not part of any section and is dropped.  CRLF line
    endings are normalized first so headings match across platforms.
    """
    doc = doc.replace("\r\n", "\n")
    sections: dict[str, str] = {}
    heading: str | None = None
    body: list[str] = []
    for line in doc.split("\n"):
        if line.startswith("## "):
            if heading is not None:
                sections[heading] = "\n".join(body)
            heading = line
            body = []
        elif heading is not None:
            body.append(line)
    if heading is not None:
        sections[heading] = "\n".join(body)
    return sections


def _normalize_section(text: str) -> str:
    """CRLF → LF and trailing-whitespace normalization for section compare."""
    return "\n".join(line.rstrip() for line in text.replace("\r\n", "\n").split("\n"))


def _is_unreleased(heading: str) -> bool:
    return heading.startswith(_UNRELEASED_HEADINGS)


def released_sections_diff(on_disk: str, fresh: str) -> list[str]:
    """Headings of fresh *released* sections that differ from the disk file.

    One-way gate (fresh → disk): every released section of the freshly
    rendered document must appear verbatim on disk.  Extra sections on disk
    (e.g. a shallow clone rendering less history) are tolerated, and the
    Unreleased section is never compared.  An empty list means "green".
    """
    disk = {
        heading: _normalize_section(body)
        for heading, body in split_sections(on_disk).items()
        if not _is_unreleased(heading)
    }
    return [
        heading
        for heading, body in split_sections(fresh).items()
        if not _is_unreleased(heading)
        and disk.get(heading) != _normalize_section(body)
    ]


def unreleased_lag(on_disk: str, fresh: str) -> int:
    """How many fresh Unreleased commits the disk file does not list yet.

    Informational only (the gate never fails on Unreleased); counts short
    hashes found in the fresh Unreleased section but missing on disk.
    """

    def _hashes(doc: str) -> set[str]:
        for heading, body in split_sections(doc).items():
            if _is_unreleased(heading):
                return set(re.findall(r"`([0-9a-f]{7})`", body))
        return set()

    return len(_hashes(fresh) - _hashes(on_disk))


def _entry_summary(
    commit: Commit, lang: str, overrides: Mapping[str, OverrideEntry]
) -> tuple[str, str | None]:
    """Return ``(displayed summary, native zh detail or None)``.

    Chinese falls back to the English summary with an inline marker when no
    human translation exists in the override table.
    """
    if lang != "zh":
        return commit.summary_en, None
    entry = overrides.get(commit.short_sha)
    if entry is None or not entry.summary:
        return f"{commit.summary_en} {_MISSING_ZH_MARK}", None
    return entry.summary, entry.detail


def _render_entry(
    commit: Commit,
    *,
    lang: str,
    remote: gitee.RemoteInfo | None,
    overrides: Mapping[str, OverrideEntry],
    pushed: Mapping[str, bool],
) -> str:
    summary, detail = _entry_summary(commit, lang, overrides)
    if remote is not None:
        link = f"([`{commit.short_sha}`]({gitee.commit_url(remote, commit.sha)}))"
    else:
        link = f"(`{commit.short_sha}`)"
    line = f"- {summary} {link}"
    if not pushed.get(commit.short_sha, True):
        line += f" {_UNPUSHED_MARKS[lang]}"
    if detail is not None:
        line += f"\n  - {detail}"
    return line


def _segment_heading(
    segment: ReleaseSegment, *, lang: str, remote: gitee.RemoteInfo | None
) -> str:
    if segment.version is None:
        heading = f"## [{_UNRELEASED_LABELS[lang]}]"
    else:
        heading = f"## [{segment.version}]"
        if segment.date:
            heading += f" - {segment.date}"
    if segment.range_from and segment.range_to and remote is not None:
        compare = gitee.compare_url(remote, segment.range_from, segment.range_to)
        heading += f" · [compare]({compare})"
    return heading


def render_document(
    segments: Iterable[ReleaseSegment],
    *,
    lang: str,
    remote: gitee.RemoteInfo | None,
    overrides: Mapping[str, OverrideEntry],
    pushed: Mapping[str, bool] | None = None,
    target: str = "root",
    generated: str | None = None,
) -> str:
    """Render one full changelog document in ``lang`` (``en`` or ``zh``).

    ``target="root"`` uses the repository header ("do not edit", sibling
    link); ``target="bundle"`` uses the end-user header for the copies
    shipped inside ``yate/resources``, where ``generated`` carries the
    one-line generation version/date note.
    """
    pushed_map: Mapping[str, bool] = pushed if pushed is not None else {}
    labels = _LABELS[lang]
    if target == "bundle":
        header = _BUNDLE_HEADERS[lang]
        if generated:
            header += f"\n\n> {generated}"
        lines: list[str] = [header, ""]
    else:
        lines = [_HEADERS[lang], ""]
    for segment in segments:
        lines.append(_segment_heading(segment, lang=lang, remote=remote))
        if segment.initial:
            lines.append("")
            lines.append(_INITIAL_NOTES[lang])
        lines.append("")
        breaking = [c for c in segment.commits if c.is_breaking]
        if breaking:
            lines.append(f"### {_BREAKING_LABELS[lang]}")
            lines.append("")
            for commit in breaking:
                lines.append(
                    _render_entry(
                        commit,
                        lang=lang,
                        remote=remote,
                        overrides=overrides,
                        pushed=pushed_map,
                    )
                )
            lines.append("")
        for category in _CATEGORY_ORDER:
            group = [
                c for c in segment.commits if c.category is category and not c.is_breaking
            ]
            if not group:
                continue
            lines.append(f"### {labels[category]}")
            lines.append("")
            for commit in group:
                lines.append(
                    _render_entry(
                        commit,
                        lang=lang,
                        remote=remote,
                        overrides=overrides,
                        pushed=pushed_map,
                    )
                )
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
