"""Bilingual Keep-a-Changelog rendering.

Both languages share one neutral model (a list of
:class:`~tools.changelog.model.ReleaseSegment`); only the label table
differs.  Output is deterministic — same input, same bytes — so ``generate
--check`` can diff against the files on disk.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping

from . import gitee
from .model import Category, Commit, ReleaseSegment
from .translations import OverrideEntry

#: Rendering order after the breaking-changes group.
_CATEGORY_ORDER: tuple[Category, ...] = (
    Category.FEATURE,
    Category.FIX,
    Category.PERFORMANCE,
    Category.REFACTOR,
    Category.DOCS,
    Category.TEST,
    Category.TOOLING,
    Category.OTHER,
)

_LABELS: dict[str, dict[Category, str]] = {
    "en": {
        Category.FEATURE: "Features",
        Category.FIX: "Bug Fixes",
        Category.PERFORMANCE: "Performance",
        Category.REFACTOR: "Refactors",
        Category.DOCS: "Documentation",
        Category.TEST: "Tests",
        Category.TOOLING: "Tooling",
        Category.OTHER: "Other Changes",
    },
    "zh": {
        Category.FEATURE: "新功能",
        Category.FIX: "问题修复",
        Category.PERFORMANCE: "性能优化",
        Category.REFACTOR: "重构",
        Category.DOCS: "文档",
        Category.TEST: "测试",
        Category.TOOLING: "构建与工程",
        Category.OTHER: "其他变更",
    },
}

_BREAKING_LABELS: dict[str, str] = {
    "en": "⚠ BREAKING CHANGES",
    "zh": "⚠ 破坏性变更",
}

_UNRELEASED_LABELS: dict[str, str] = {"en": "Unreleased", "zh": "未发布"}

_INITIAL_NOTES: dict[str, str] = {
    "en": "_Initial release._",
    "zh": "_首个版本。_",
}

_HEADERS: dict[str, str] = {
    "en": (
        "# Changelog\n"
        "\n"
        "> Generated by `python -m tools.changelog` — do not edit by hand.\n"
        "> Chinese edition: [CHANGELOG.zh.md](CHANGELOG.zh.md)"
    ),
    "zh": (
        "# 变更日志\n"
        "\n"
        "> 本文件由 `python -m tools.changelog` 自动生成 —— 请勿手工编辑。\n"
        "> 英文版：[CHANGELOG.md](CHANGELOG.md)"
    ),
}

_MISSING_ZH_MARK = "[缺中文]"
_UNPUSHED_MARKS: dict[str, str] = {"en": "(unpushed)", "zh": "(本地未推送)"}


def _entry_summary(
    commit: Commit, lang: str, overrides: Mapping[str, OverrideEntry]
) -> tuple[str, str | None]:
    """Return ``(displayed summary, native zh detail or None)``.

    Chinese falls back to the English summary with an inline marker when no
    human translation exists in the override table.
    """
    if lang != "zh":
        return commit.summary_en, None
    entry = overrides.get(commit.short_sha)
    if entry is None or not entry.summary:
        return f"{commit.summary_en} {_MISSING_ZH_MARK}", None
    return entry.summary, entry.detail


def _render_entry(
    commit: Commit,
    *,
    lang: str,
    remote: gitee.RemoteInfo | None,
    overrides: Mapping[str, OverrideEntry],
    pushed: Mapping[str, bool],
) -> str:
    summary, detail = _entry_summary(commit, lang, overrides)
    if remote is not None:
        link = f"([`{commit.short_sha}`]({gitee.commit_url(remote, commit.sha)}))"
    else:
        link = f"(`{commit.short_sha}`)"
    line = f"- {summary} {link}"
    if not pushed.get(commit.short_sha, True):
        line += f" {_UNPUSHED_MARKS[lang]}"
    if detail is not None:
        line += f"\n  - {detail}"
    return line


def _segment_heading(
    segment: ReleaseSegment, *, lang: str, remote: gitee.RemoteInfo | None
) -> str:
    if segment.version is None:
        heading = f"## [{_UNRELEASED_LABELS[lang]}]"
    else:
        heading = f"## [{segment.version}]"
        if segment.date:
            heading += f" - {segment.date}"
    if segment.range_from and segment.range_to and remote is not None:
        compare = gitee.compare_url(remote, segment.range_from, segment.range_to)
        heading += f" · [compare]({compare})"
    return heading


def render_document(
    segments: Iterable[ReleaseSegment],
    *,
    lang: str,
    remote: gitee.RemoteInfo | None,
    overrides: Mapping[str, OverrideEntry],
    pushed: Mapping[str, bool] | None = None,
) -> str:
    """Render one full changelog document in ``lang`` (``en`` or ``zh``)."""
    pushed_map: Mapping[str, bool] = pushed if pushed is not None else {}
    labels = _LABELS[lang]
    lines: list[str] = [_HEADERS[lang], ""]
    for segment in segments:
        lines.append(_segment_heading(segment, lang=lang, remote=remote))
        if segment.initial:
            lines.append("")
            lines.append(_INITIAL_NOTES[lang])
        lines.append("")
        breaking = [c for c in segment.commits if c.is_breaking]
        if breaking:
            lines.append(f"### {_BREAKING_LABELS[lang]}")
            lines.append("")
            for commit in breaking:
                lines.append(
                    _render_entry(
                        commit,
                        lang=lang,
                        remote=remote,
                        overrides=overrides,
                        pushed=pushed_map,
                    )
                )
            lines.append("")
        for category in _CATEGORY_ORDER:
            group = [
                c for c in segment.commits if c.category is category and not c.is_breaking
            ]
            if not group:
                continue
            lines.append(f"### {labels[category]}")
            lines.append("")
            for commit in group:
                lines.append(
                    _render_entry(
                        commit,
                        lang=lang,
                        remote=remote,
                        overrides=overrides,
                        pushed=pushed_map,
                    )
                )
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
